export const ROBO_MODELS_CSS = `
.roboModels{display:grid;gap:20px;width:100%;max-width:760px;box-sizing:border-box;container-type:inline-size;color:var(--dsw-alias-label-primary)}
.roboModels>header{display:flex;align-items:center;min-height:32px}.roboModels h2,.roboModels h3,.roboModels p{margin:0}.roboModels h2{font-size:22px;line-height:32px}.roboModels h3{font-size:16px;line-height:24px}.roboModelsIntro,.roboModelsHint{color:var(--dsw-alias-label-secondary);line-height:1.55}.roboModelsBack{justify-self:start}
.roboModelsCard{display:grid;gap:16px;padding:18px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;background:var(--dsw-alias-bg-layer-1)}
.roboModelsOfficial{gap:14px}.roboModelsOfficialHead{display:flex;align-items:center;justify-content:space-between;gap:16px}.roboModelsOfficialBody,.roboModelsToolbarCopy{display:grid;gap:4px;min-width:0}.roboModelsTitleLine{display:flex;align-items:center;gap:8px;min-width:0}.roboModelsOfficialHead>.roboModelsButton{flex:none;white-space:nowrap}.roboModelsOfficialModels{border-top:1px solid var(--dsw-alias-border-l1);padding-top:4px}
.roboModelsToolbar,.roboModelsRowHead,.roboModelsActions{display:flex;align-items:center;justify-content:space-between;gap:10px;min-width:0}.roboModelsToolbar{min-height:44px}.roboModelsRowHead>:first-child{min-width:0}.roboModelsActions{justify-content:flex-end;flex-wrap:wrap}.roboModelsActions>.roboModelsHint{margin-right:auto}.roboModelsToolbar>.roboModelsButton,.roboModelsRowHead>.roboModelsActions{flex:none}
.roboModelsButton{display:inline-flex;align-items:center;justify-content:center;box-sizing:border-box;min-height:44px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;padding:7px 12px;background:transparent;color:inherit;font:inherit;line-height:24px;cursor:pointer}.roboModelsButton:hover{background:var(--dsw-alias-interactive-bg-hover)}
.roboModelsButtonPrimary{border-color:transparent;background:var(--dsw-alias-button-primary-fill);color:var(--dsw-alias-label-primary-foreground);font-weight:600}.roboModelsButtonDanger{color:var(--dsw-alias-state-error-primary,#b42318)}.roboModelsButton:disabled{opacity:.45;cursor:default}
.roboModelsList{display:grid;gap:12px}.roboModelsProvider{gap:12px}.roboModelsMeta{display:flex;gap:5px 10px;flex-wrap:wrap;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:20px}.roboModelsEndpoint{color:var(--dsw-alias-label-secondary);font-size:14px;line-height:20px;overflow-wrap:anywhere}.roboModelsModelList{display:grid;margin:0;padding:0;list-style:none}.roboModelsModel{box-sizing:border-box;display:flex;align-items:center;justify-content:space-between;gap:16px;min-height:48px;padding:6px 0;border-bottom:1px solid var(--dsw-alias-border-l1)}.roboModelsModel:last-child{border-bottom:0}.roboModelsModelName{min-width:0;overflow-wrap:anywhere;font-size:16px;line-height:24px}.roboModelsDefaultBadge{flex:none;padding:2px 8px;border-radius:999px;background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-secondary);font-size:12px;line-height:20px}.roboModelsSetDefault{flex:none;min-height:32px;border:0;border-radius:8px;padding:4px 8px;background:transparent;color:var(--dsw-alias-brand-primary);font:inherit;font-size:14px;line-height:20px;cursor:pointer}.roboModelsSetDefault:hover{background:var(--dsw-alias-interactive-bg-hover)}.roboModelsSetDefault:disabled{opacity:.45;cursor:default}.roboModelsCard>.roboModelsHint{overflow-wrap:anywhere}
.roboModelsDisclosure{min-width:0}.roboModelsDisclosure>summary{display:flex;align-items:center;gap:10px;min-height:40px;cursor:pointer;list-style:none;font-size:14px}.roboModelsDisclosure>summary::-webkit-details-marker{display:none}.roboModelsDisclosure>summary::before{content:'›';font-size:20px;line-height:20px;color:var(--dsw-alias-label-secondary);transform-origin:center;flex:none}.roboModelsDisclosure[open]>summary::before{transform:rotate(90deg)}.roboModelsDisclosure>summary>span:first-of-type{flex:none}.roboModelsCount{margin-left:5px;color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums}.roboModelsDisclosureHint{margin-left:auto;color:var(--dsw-alias-label-secondary);font-size:13px;overflow-wrap:anywhere;text-align:right}.roboModelsDisclosure[open]>.roboModelsModelList{border-top:1px solid var(--dsw-alias-border-l1)}
.roboModelsForm{display:grid;gap:16px}.roboModelsGrid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px}.roboModelsField{display:grid;gap:6px;min-width:0}.roboModelsFieldWide{grid-column:1/-1}.roboModelsField label{font-size:14px;color:var(--dsw-alias-label-secondary)}
.roboModelsInput{box-sizing:border-box;width:100%;min-width:0;min-height:44px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;padding:9px 11px;background:var(--dsw-alias-bg-layer-1);color:inherit;font:inherit}.roboModelsInput:focus{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:1px}.roboModels textarea.roboModelsInput{min-height:128px;resize:vertical}
.roboModelsProtocol{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.roboModelsProtocol label{display:flex;align-items:center;box-sizing:border-box;min-height:44px;gap:6px;padding:9px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;color:inherit;font-size:14px;overflow-wrap:anywhere}.roboModelsProtocol label:has(input:checked){border-color:var(--dsw-alias-brand-primary);background:var(--dsw-alias-interactive-bg-hover)}
.roboModelsStatus{padding:9px 11px;border-radius:12px;background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-secondary);font-size:14px}.roboModelsError{color:var(--dsw-alias-state-error-primary,#b42318)!important}.roboModelsEmpty{padding:22px;text-align:center;border:1px dashed var(--dsw-alias-border-l1);border-radius:14px;color:var(--dsw-alias-label-secondary)}
.roboModels :focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}
@container(max-width:520px){.roboModelsGrid{grid-template-columns:1fr}.roboModelsFieldWide{grid-column:auto}.roboModelsProtocol{grid-template-columns:1fr}.roboModelsToolbar,.roboModelsRowHead{align-items:flex-start}.roboModelsCard{padding:16px}.roboModelsOfficialHead{align-items:flex-start}.roboModelsRowHead{flex-direction:column}.roboModelsRowHead>.roboModelsActions{align-self:stretch}.roboModelsModel{gap:10px}}
@container(max-width:400px){.roboModelsOfficialHead{flex-direction:column;gap:12px}.roboModelsOfficialHead>.roboModelsButton{align-self:flex-end}.roboModelsToolbar{flex-wrap:wrap}.roboModelsToolbar>.roboModelsButton{margin-left:auto}}
`

export function installRoboModelsStyles(): () => void {
  if (typeof document === 'undefined' || document.getElementById('robo-models-style')) return () => {}
  const style = document.createElement('style'); style.id = 'robo-models-style'; style.textContent = ROBO_MODELS_CSS
  document.head.append(style)
  return () => { style.remove() }
}
