export const ROBO_SIDEBAR_ACCOUNT_CSS = `
body[data-dsh-desktop-mode="extended"] [data-slot="sidebar.footer.action"]:has(.roboSidebarAccount){scrollbar-gutter:auto}
/* Keep the original panel owners mounted; only their launcher rows are folded away. */
body:has(.roboSidebarAccount) [data-slot="sidebar.settings"] > div:has(> button[aria-haspopup="dialog"]){display:none}
body:has(.roboSidebarAccount) [data-slot="sidebar.footer.action"] span:has(> button[aria-label="手机连接"]){display:none}
.roboSidebarAccount{width:100%;min-width:0;padding:6px 0 2px;color:var(--dsw-alias-label-primary)}
.roboSidebarAccountCard{box-sizing:border-box;display:flex;align-items:center;gap:10px;width:100%;min-height:48px;padding:6px 8px;border:0;border-radius:8px;background:transparent;color:inherit;font:inherit;cursor:pointer;text-align:left}
.roboSidebarAccountCard:hover,.roboSidebarAccountCard[data-popup-open]{background:color-mix(in srgb,var(--dsw-alias-label-primary) 10%,transparent)}
.roboSidebarAvatar{flex:none;width:32px;height:32px;display:grid;place-items:center;border-radius:50%;corner-shape:round;background:color-mix(in srgb,var(--dsw-alias-label-primary) 10%,transparent);border:0;color:var(--dsw-alias-label-primary);font-size:17px;font-weight:600}
.roboSidebarAccountCopy{display:grid;gap:1px;flex:1;min-width:0;line-height:1.35}.roboSidebarAccountCopy strong{font-size:15px;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.roboSidebarAccountCopy>span{font-size:13px;color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums}
.roboSidebarAccount[data-wide=false]{border:0;padding:0;display:flex;justify-content:center}.roboSidebarAccount[data-wide=false] .roboSidebarAccountCard{width:38px;padding:0;border:0;border-radius:50%;corner-shape:round;background:transparent}.roboSidebarAccountCard>svg{flex:none;color:var(--dsw-alias-label-secondary)}
.roboAccountMenuPositioner{z-index:1100}.roboAccountMenu{box-sizing:border-box;width:max(240px,var(--anchor-width));max-width:calc(100vw - 24px);padding:10px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);box-shadow:0 12px 36px #0003;font:15px/1.45 system-ui,sans-serif}
.roboAccountMenuTitle{font-size:15px;margin:7px 9px;font-weight:600;overflow-wrap:anywhere}.roboAccountMenuBalance{display:flex;justify-content:space-between;gap:8px;font-size:13px;margin:0 9px 12px;color:var(--dsw-alias-label-secondary)}.roboAccountMenuBalance strong{color:var(--dsw-alias-label-primary);font-variant-numeric:tabular-nums}
.roboAccountMenu button,.roboAccountMenu a{box-sizing:border-box;width:100%;display:flex;align-items:center;gap:10px;padding:9px 10px;border:0;border-radius:6px;background:transparent;color:inherit;font:inherit;text-align:left;cursor:pointer;text-decoration:none}.roboAccountMenu button:hover,.roboAccountMenu a:hover{background:var(--dsw-alias-interactive-bg-hover)}.roboAccountMenu button:disabled{opacity:.5;cursor:default}.roboAccountMenu button svg,.roboAccountMenu a svg{flex:none;color:var(--dsw-alias-label-secondary)}
.roboAccountMenuDivider{height:1px;background:var(--dsw-alias-border-l1);margin:5px 0}.roboAccountMenuError{font-size:13px;margin:8px;color:var(--dsw-alias-state-error-primary);overflow-wrap:anywhere}
.roboAccountDialogBackdrop{position:fixed;inset:0;background:#0006;z-index:1200}.roboAccountDialog{box-sizing:border-box;position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);z-index:1201;width:650px;max-width:calc(100vw - 32px);max-height:calc(100dvh - 48px);overflow:auto;padding:28px;border-radius:24px;border:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);box-shadow:0 24px 80px #0004}
.roboAccountDialogClose{position:absolute;right:28px;top:28px;display:grid;place-items:center;width:32px;height:32px;border:0;border-radius:8px;background:transparent;color:inherit;cursor:pointer}.roboAccountDialogClose:hover{background:var(--dsw-alias-interactive-bg-hover)}
.roboAccountVisuallyHidden{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
.roboSidebarAccount :focus-visible,.roboAccountMenu :focus-visible,.roboAccountDialog :focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}
`
