import { ROBO_SKILL_MARKET_CSS } from './robo-skill-market-styles.ts'

/** Extend the existing Desktop theme without a second token system. */
export const ROBO_SKILLS_CSS = `
.roboSkillTrigger,.roboDeviceTrigger,.roboSkillIcon,.roboSkillChip button,.roboSkillResult button { display:inline-flex;align-items:center;justify-content:center;gap:5px;border:0;background:transparent;color:var(--dsw-alias-label-secondary);font:inherit;cursor:pointer; }
.roboDeviceTrigger { padding:4px 6px;white-space:nowrap;border-radius:7px;min-height:28px;font-size:14px; }.roboDeviceTrigger:hover { background:var(--dsw-alias-interactive-bg-hover); }
.roboSkillTrigger { padding:4px 6px;white-space:nowrap;border-radius:7px;min-height:28px;font-size:14px; }
.roboSkillTrigger:hover,.roboSkillIcon:hover { background:var(--dsw-alias-interactive-bg-hover); }.roboSkillTrigger:disabled { opacity:.45;cursor:default; }
.roboSkillPositioner { z-index:1000;width:min(var(--anchor-width),calc(100vw - 32px));max-width:calc(100vw - 32px); }
.roboSkillPopup { box-sizing:border-box;width:100%;max-height:min(500px,var(--available-height,80vh));overflow:auto;border:1px solid var(--dsw-alias-border-l1);border-radius:18px;padding:14px;background:var(--dsw-specific-input-major,var(--dsw-alias-bg-layer-1,#fff));color:var(--dsw-alias-label-primary,#222);box-shadow:0 18px 48px #0000002e,0 2px 8px #0000001a;font:14px/1.5 system-ui,sans-serif;transform-origin:var(--transform-origin); }
.roboSkillHeader { display:flex;align-items:center;gap:10px;padding:0 2px 10px; }.roboSkillHeader>div { min-width:0; }.roboSkillHeader h2 { font-size:16px;line-height:22px;font-weight:650;margin:0; }.roboSkillHeader p { margin:1px 0 0;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px; }.roboSkillHeader .roboSkillIcon { margin-left:auto;min-width:30px;min-height:30px;border-radius:9px; }
.roboSkillBadge { color:var(--dsw-alias-label-secondary);border:1px solid var(--dsw-alias-border-l1);border-radius:5px;padding:1px 6px;font-size:13px; }
.roboSkillDescription,.roboSkillDetail p { color:var(--dsw-alias-label-secondary);font-size:14px;line-height:1.6;margin:6px 0 16px; }
.roboSkillSearch { display:flex;align-items:center;gap:8px;min-height:38px;box-sizing:border-box;padding:7px 11px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;background:var(--dsw-alias-bg-layer-1,#fff);color:var(--dsw-alias-label-secondary); }
.roboSkillSearch input { min-width:0;width:100%;border:0;outline:none;background:transparent;color:var(--dsw-alias-label-primary);font:13px/20px system-ui,sans-serif; }.roboSkillSearch input::placeholder { color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary)); }
.roboSkillFilters { display:flex;flex-direction:column;gap:14px;margin-top:0; }.roboSkillFilters label { flex:1;min-width:0;display:flex;flex-direction:column;gap:7px;font-size:14px;color:var(--dsw-alias-label-secondary); }
.roboSkillFilters select { width:100%;border:1px solid var(--dsw-alias-border-l1);box-sizing:border-box;border-radius:10px;padding:10px 12px;background:var(--dsw-alias-bg-layer-1,#fff);color:var(--dsw-alias-label-primary,#222);font:16px/1.5 system-ui,sans-serif;min-height:48px; }
.roboSkillList { margin-top:8px;max-height:280px;overflow:auto;padding:2px; }.roboSkillRow { position:relative;width:100%;display:grid;grid-template-columns:34px minmax(0,1fr);align-items:center;gap:10px;min-height:58px;justify-content:center;padding:9px 12px 9px 14px;text-align:left;border:1px solid transparent;border-radius:12px;background:transparent;color:inherit;font:inherit;cursor:pointer;transition:background-color 100ms ease,border-color 100ms ease; }.roboSkillRow::before { content:'';position:absolute;left:5px;top:14px;bottom:14px;width:2px;border-radius:2px;background:transparent; }.roboSkillRow:hover,.roboSkillRow[data-selected=true] { background:var(--dsw-alias-interactive-bg-hover);border-color:var(--dsw-alias-border-l1); }.roboSkillRow:hover::before,.roboSkillRow[data-selected=true]::before { background:var(--dsw-alias-state-business-primary,var(--dsw-alias-brand-primary,#3267d6)); }
.roboSkillRowIcon { width:34px;height:34px;display:grid;place-items:center;overflow:hidden;border-radius:10px;color:var(--dsw-alias-brand-primary,#3267d6);background:color-mix(in srgb,var(--dsw-alias-brand-primary,#3267d6) 10%,transparent); }.roboSkillRowIcon svg { width:17px;height:17px; }.roboSkillRowIcon .roboSkillIconImage { width:100%;height:100%;object-fit:cover;display:block; }.roboSkillRowCopy { min-width:0;display:grid;gap:3px; }
.roboSkillRowTitle { display:flex;justify-content:space-between;align-items:center;gap:12px;width:100%;min-width:0;overflow-wrap:anywhere; }.roboSkillRowTitle strong { min-width:0;font-size:14px;line-height:20px;font-weight:600; }.roboSkillRowTitle small { flex-shrink:0;font-weight:400;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:18px;padding:0 6px;border:1px solid var(--dsw-alias-border-l1);border-radius:999px; }
.roboSkillRowDescription { display:-webkit-box;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px; }
.roboSkillDetail { padding-top:18px;margin-top:14px;border-top:1px solid var(--dsw-alias-border-l1); }.roboSkillDetail>small { display:block;color:var(--dsw-alias-label-secondary); }
.roboSkillPrimary { width:100%;min-height:48px;padding:12px 16px;border:0;border-radius:12px;font:inherit;font-weight:600;background:var(--dsw-alias-button-primary-fill,#3267d6);color:var(--dsw-alias-label-primary-foreground,#fff);cursor:pointer; }.roboSkillPrimary:disabled { opacity:.45;cursor:default; }
.roboSkillFooter { display:flex;align-items:center;justify-content:flex-start;gap:4px;margin-top:8px;padding-top:9px;border-top:1px solid var(--dsw-alias-border-l1);color:var(--dsw-alias-label-secondary);font-size:12px; }.roboSkillFooter button,.roboSkillEmpty button { background:transparent;color:inherit;font:inherit;border:0;text-decoration:none;cursor:pointer;padding:6px 8px;border-radius:8px;min-height:30px; }.roboSkillFooter button:last-child { margin-left:auto; }
.roboSkillFooter button:hover { background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary); }
.roboSkillDetail p { margin:14px 0; }
.roboSkillPopup .roboSkillSearch input:focus-visible { outline:none; }
.roboSkillEmpty { padding:20px 8px;text-align:center;color:var(--dsw-alias-label-secondary); }.roboSkillEmpty button { display:block;margin:8px auto 0; }.roboSkillError { margin:12px 0 0;color:var(--dsw-alias-state-warning-primary,#a34d14); }
.roboSkillChip { display:inline-flex;align-items:center;gap:3px;padding:2px 4px;border:1px solid var(--dsw-alias-border-l1);border-radius:6px;max-width:160px;min-width:0;font-size:13px; }.roboSkillChip>span { flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap; }.roboSkillChip button { flex:0 0 26px;width:26px;height:24px;padding:0;white-space:nowrap; }
.roboSkillResult { padding:10px 12px;margin-top:8px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-1);font:14px/1.6 system-ui;max-height:230px;overflow:auto;overflow-wrap:anywhere; }.roboSkillResult p { margin:0; }.roboSkillResult ul { margin:8px 0;padding-left:18px; }
.roboSkillPopup :focus-visible,.roboSkillTrigger:focus-visible,.roboSkillChip button:focus-visible,.roboSkillResult button:focus-visible { outline:2px solid var(--dsw-alias-state-business-primary,#3267d6);outline-offset:2px; }.roboSkillPopup .roboSkillSearch:focus-within { border-color:var(--dsw-alias-state-business-primary,#3267d6);outline:none;box-shadow:0 0 0 3px color-mix(in srgb,var(--dsw-alias-state-business-primary,#3267d6) 16%,transparent); }
@media(max-width:600px) { .roboSkillFilters { flex-direction:column; }.roboSkillChip { max-width:110px; }.roboSkillPositioner { width:calc(100vw - 32px); } }
`
export function installRoboSkillsStyles(): () => void {
  if (typeof document === 'undefined' || document.getElementById('robo-skills-style')) return () => {}
  const style = document.createElement('style'); style.id = 'robo-skills-style'; style.textContent = ROBO_SKILLS_CSS + ROBO_SKILL_MARKET_CSS
  document.head.appendChild(style)
  return () => { style.remove() }
}
