/** Skill market and device directory share only product-shell primitives. */
export const ROBO_SKILL_MARKET_CSS = `
.roboMarket { height:100%;min-height:0;overflow:auto;box-sizing:border-box;background:var(--dsw-alias-bg-layer-0);color:var(--dsw-alias-label-primary);font:16px/1.55 system-ui,sans-serif; }
.roboDeviceHeader { display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;column-gap:20px;border-bottom:1px solid var(--dsw-alias-border-l1);margin-bottom:0; }
.roboDeviceHeaderTools { display:contents; }
.roboDevices .roboDeviceHeader .roboSkillSearch { justify-self:end;width:220px;height:32px;min-height:32px;min-width:0;max-width:100%;font-size:13px;line-height:20px;padding:0 11px;border-radius:999px; }
.roboDevices .roboDeviceHeader .roboSkillSearch input { height:20px;line-height:20px;padding:0; }
.roboDeviceHeader .roboSkillSearch svg { flex-shrink:0;width:15px;height:15px; }
.roboDeviceFamilies { display:flex;gap:8px;overflow-x:auto;padding:20px 0 14px; }
.roboDeviceFamilies button { flex-shrink:0;padding:6px 12px;border:0;border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary);font-size:14px; }
.roboDeviceFamilies button[aria-selected=true] { background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1));color:var(--dsw-alias-label-primary);font-weight:600; }
@media(max-width:600px) { .roboDeviceHeader { grid-template-columns:auto minmax(0,1fr);column-gap:14px;padding-bottom:8px; } .roboDeviceHeader .roboDeviceHeadingActions { grid-column:2;justify-content:flex-end; } }
.roboDeviceTabs { display:flex;align-items:center;gap:24px;height:48px; }
.roboDeviceTabs button { position:relative;display:inline-flex;align-items:center;height:48px;border:0;background:transparent;color:var(--dsw-alias-label-secondary);padding:0;font-size:14px;line-height:20px; }
.roboDeviceTabs button[aria-selected=true] { color:var(--dsw-alias-label-primary);font-weight:600; }
.roboDeviceTabs button[aria-selected=true]::after { content:"";position:absolute;bottom:0;left:0;right:0;height:2px;background:currentColor; }
.roboDeviceHeader .roboDeviceHeadingActions { font-size:13px; }
.roboMarket * { box-sizing:border-box; }
.roboMarketInner { max-width:1420px;margin:0 auto;padding:22px 34px 52px; }
.roboMarket button,.roboMarket input,.roboMarket select { font:inherit; }
.roboMarket button { cursor:pointer; }
.roboMarket button:disabled { opacity:.5;cursor:default; }
.roboMarket button:focus-visible,.roboMarket select:focus-visible,.roboMarket h1:focus-visible,.roboMarket .roboSkillSearch:focus-within,.roboMarketCard:focus-visible { outline:2px solid var(--dsw-alias-brand-primary,#3267d6);outline-offset:3px; }
.roboMarketTop,.roboMarketHeading,.roboMarketDetailHeading { display:flex;align-items:center;justify-content:space-between;gap:22px; }
.roboMarketTop { display:grid;grid-template-columns:auto minmax(0,1fr) auto auto;align-items:center;gap:12px;min-height:48px;border-bottom:1px solid var(--dsw-alias-border-l1); }
.roboMarketTopActions,.roboDeviceHeadingActions { display:flex;align-items:center;gap:12px; }
.roboMarketPrimaryTabs { display:flex;align-items:center;height:48px; }
.roboMarketTop > .roboMarketTopActions { display:contents; }
.roboMarketPrimaryTabs button { position:relative;display:inline-flex;align-items:center;height:48px;line-height:20px;padding:0 3px;border:0;background:transparent;color:var(--dsw-alias-label-primary);font-size:15px;font-weight:650; }
.roboMarketPrimaryTabs button::after { content:"";position:absolute;bottom:0;left:0;right:0;height:2px;background:currentColor; }
.roboMarket .roboMarketTop .roboSkillSearch { justify-self:end;width:220px;max-width:100%;min-width:0;height:32px;min-height:32px;padding:0 11px;border-radius:999px;font-size:13px;line-height:20px; }
.roboMarketTop .roboSkillSearch input { height:20px;padding:0;line-height:20px; }
.roboMarketTop .roboSkillSearch svg { width:15px;height:15px;flex-shrink:0; }
.roboMarket .roboMarketTop .roboMarketMine,.roboMarket .roboMarketTop .roboMarketCreate { height:32px;padding:0 10px;font-size:13px;line-height:20px; }
.roboMarketBack,.roboMarketLink { display:inline-flex;align-items:center;gap:7px;padding:6px 0;background:transparent;border:0;color:var(--dsw-alias-label-secondary);white-space:nowrap; }
.roboMarketBack:hover,.roboMarketLink:hover { color:var(--dsw-alias-label-primary); }
.roboMarketHeading { padding:28px 0 20px;align-items:flex-end; }
.roboMarket h1 { font-size:30px;line-height:1.2;letter-spacing:-.025em;margin:7px 0 7px; }
.roboMarketHeading p,.roboMarketDetailHeading p { color:var(--dsw-alias-label-secondary);margin:0; }
.roboMarketEyebrow { display:flex;align-items:center;gap:7px;font-size:13px;color:var(--dsw-alias-label-secondary); }
.roboMarket .roboSkillSearch { display:flex;align-items:center;gap:8px;min-width:260px;padding:8px 11px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary); }
.roboMarket .roboSkillSearch input { min-width:0;flex:1;border:0;outline:0;background:transparent;color:var(--dsw-alias-label-primary); }
.roboMarketMine { display:inline-flex;align-items:center;gap:7px;padding:8px 11px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary); }
.roboMarketMine[aria-pressed=true] { border-color:var(--dsw-alias-brand-primary,#3267d6);color:var(--dsw-alias-brand-primary,#3267d6); }
.roboMarketMine span { min-width:18px;text-align:center;color:var(--dsw-alias-label-secondary); }
.roboMarketCreate { display:inline-flex;align-items:center;gap:6px;padding:8px 11px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);text-decoration:none;white-space:nowrap; }
.roboMarketCreate:hover { background:var(--dsw-alias-interactive-bg-hover); }
.roboMarketRobot { display:flex;align-items:center;gap:10px;font-size:14px;color:var(--dsw-alias-label-secondary); }
.roboMarketRobot select { max-width:220px;padding:7px 10px;border:1px solid var(--dsw-alias-border-l1);border-radius:9px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary); }
.roboMarketFilters { display:flex;align-items:center;justify-content:space-between;gap:10px 18px;flex-wrap:wrap;padding:20px 0 10px;border-bottom:1px solid var(--dsw-alias-border-l1); }
.roboMarketCategories { min-width:0;display:flex;align-items:center;gap:4px;flex-wrap:wrap; }
.roboMarketCategories button { flex:0 0 auto;padding:7px 13px;border:0;border-radius:9px;color:var(--dsw-alias-label-secondary);background:transparent;font-size:14px; }
.roboMarketCategories button:hover,.roboMarketCategories button[aria-pressed=true] { background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary);font-weight:600; }
.roboMarketMore { position:relative;flex:0 0 auto;color:var(--dsw-alias-label-secondary);font-size:14px; }
.roboMarketMore summary { display:flex;align-items:center;gap:4px;padding:7px 10px;border-radius:9px;cursor:pointer;list-style:none;white-space:nowrap; }
.roboMarketMore summary::-webkit-details-marker { display:none; }
.roboMarketMore summary:hover,.roboMarketMore[open] summary { background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary); }
.roboMarketMore>div { position:absolute;z-index:20;top:calc(100% + 6px);right:0;min-width:150px;display:grid;gap:2px;padding:6px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px;background:var(--dsw-alias-bg-layer-1);box-shadow:0 14px 36px rgba(0,0,0,.18); }
.roboMarketMore>div button { width:100%;text-align:left; }
.roboMarketCount { color:var(--dsw-alias-label-secondary);font-size:13px;margin:16px 0 4px; }
.roboMarketGroup { padding:20px 0 23px; }
.roboMarketGroup+.roboMarketGroup { border-top:1px solid var(--dsw-alias-border-l1); }
.roboMarketGroup>h2 { margin:0 0 14px;font-size:20px;letter-spacing:-.01em; }
.roboMarketCards { display:grid;grid-template-columns:repeat(auto-fill,minmax(248px,1fr));column-gap:14px;row-gap:14px; }
.roboMarketCard { min-width:0;min-height:148px;display:flex;flex-direction:column;gap:12px;padding:14px 15px 12px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;background:var(--dsw-alias-bg-layer-1);cursor:pointer;transition:border-color .16s ease,background .16s ease,box-shadow .16s ease; }
.roboMarketCard:hover,.roboMarketCard:focus-visible { border-color:color-mix(in srgb,var(--dsw-alias-brand-primary,#3267d6) 46%,var(--dsw-alias-border-l1));background:var(--dsw-alias-interactive-bg-hover);box-shadow:0 5px 16px rgba(0,0,0,.09); }
.roboMarketIcon { width:40px;height:40px;display:grid;place-items:center;flex:0 0 auto;border:1px solid color-mix(in srgb,currentColor 24%,transparent);border-radius:11px;background:color-mix(in srgb,currentColor 9%,transparent); }
.roboMarketIcon svg { width:19px;height:19px; }.roboMarketIconImage { width:100%;height:100%;object-fit:cover;border-radius:inherit;display:block; }
.roboMarketIcon0 { color:#3b82f6; }.roboMarketIcon1 { color:#8b5cf6; }.roboMarketIcon2 { color:#0ea5a8; }.roboMarketIcon3 { color:#e88a17; }
button.roboMarketIcon { padding:0; }
.roboMarketCardHeader { display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:10px; }.roboMarketCardKicker { min-width:0;display:flex;flex-direction:column;gap:2px;color:var(--dsw-alias-label-secondary);font-size:11px; }.roboMarketCardKicker span:first-child { color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary));font-size:10px;font-weight:600; }.roboMarketCardKicker span:last-child { overflow:hidden;text-overflow:ellipsis;white-space:nowrap; }.roboMarketCardAction { justify-self:end; }.roboMarketCardCopy { min-width:0;padding-top:0; }.roboMarketCardLabel { display:none; }.roboMarketCard h3 { margin:0 0 5px;font-size:16px;line-height:1.25;letter-spacing:-.01em; }
.roboMarketCard h3 button { display:-webkit-box;max-width:100%;padding:0;border:0;background:transparent;color:inherit;font-weight:650;text-align:left;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2;line-clamp:2; }
.roboMarketCard h3 button:hover { text-decoration:underline;text-underline-offset:3px; }
.roboMarketCard p { display:-webkit-box;margin:0;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:1.42;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2;line-clamp:2; }.roboMarketCardFooter { display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:auto;padding-top:9px;border-top:1px solid var(--dsw-alias-border-l1); }.roboMarketScope { display:block;margin-top:0;color:var(--dsw-alias-label-secondary);font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap; }.roboMarketCardOpen { flex:none;color:var(--dsw-alias-brand-primary,#3267d6);font-size:11px;font-weight:650; }
.roboMarketAdd,.roboMarketAdded { display:inline-flex;align-items:center;justify-content:center;gap:5px;border:1px solid var(--dsw-alias-border-l1);padding:5px 8px;border-radius:7px;font-size:12px!important;white-space:nowrap; }
.roboMarketAdd { color:var(--dsw-alias-label-primary-foreground,#fff);background:var(--dsw-alias-button-primary-fill,#3267d6);border-color:transparent; }
.roboMarketAdded { color:var(--dsw-alias-label-primary);background:transparent; }
.roboMarketAdd:hover { filter:brightness(1.08); }.roboMarketAdded:hover { background:var(--dsw-alias-interactive-bg-hover); }
.roboMarketNote { color:var(--dsw-alias-label-secondary);font-size:13px;margin-top:20px; }
.roboMarketEmpty { padding:54px 16px;text-align:center;color:var(--dsw-alias-label-secondary); }.roboMarketEmpty h2 { font-size:20px;color:var(--dsw-alias-label-primary); }.roboMarketEmpty .roboMarketAdd { margin-top:12px; }
.roboMarketFeedback { display:flex;align-items:center;gap:8px;padding:11px 13px;margin:16px 0 0;border:1px solid var(--dsw-alias-border-l1);border-radius:9px;background:var(--dsw-alias-bg-layer-1);font-size:14px; }.roboMarketFeedback button { margin-left:auto;display:flex;align-items:center;background:transparent;border:0;color:inherit; }.roboMarketFeedback[role=alert] { color:var(--dsw-alias-state-warning-primary,#a34d14); }
.roboMarketModalBackdrop { position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:24px;background:rgba(8,15,28,.68);backdrop-filter:blur(14px) saturate(115%);-webkit-backdrop-filter:blur(14px) saturate(115%); }
.roboMarketModal { position:relative;width:min(760px,calc(100vw - 48px));max-height:min(720px,calc(100vh - 48px));display:flex;flex-direction:column;overflow:hidden;padding:28px 30px 30px;border:1px solid var(--dsw-alias-border-l1);border-radius:18px;background:var(--dsw-alias-bg-layer-1,#151a24);box-shadow:0 24px 70px rgba(0,0,0,.34); }
.roboMarketModalClose { position:absolute;top:18px;right:18px;z-index:1;display:grid;place-items:center;width:32px;height:32px;padding:0;border:1px solid transparent;border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary);line-height:1;cursor:pointer;transition:background .16s ease,color .16s ease,border-color .16s ease; }
.roboMarketModalClose:hover { border-color:var(--dsw-alias-border-l1);background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary); }
.roboMarketModalClose:focus-visible { outline:2px solid var(--dsw-alias-brand-primary,#6ea0ff);outline-offset:2px; }
.roboMarketDetailHeading { justify-content:flex-start;align-items:flex-start;padding:0 46px 24px 0;border-bottom:1px solid var(--dsw-alias-border-l1); }.roboMarketDetailHeading>div { min-width:0;padding-top:2px; }.roboMarketDetailHeading .roboMarketIcon { flex:none;width:64px;height:64px;border-radius:18px; }.roboMarketDetailHeading h1 { font-size:28px;line-height:1.2;margin:5px 0 7px;letter-spacing:-.025em; }
.roboMarketModalBody { min-height:0;overflow:auto;padding:0 6px 4px 0; }
.roboMarketPublisher { display:flex;align-items:center;gap:12px;margin:18px 0 2px;padding:12px 14px;border:1px solid var(--dsw-alias-border-l1);border-left:3px solid var(--dsw-alias-brand-primary,#3267d6);border-radius:12px;background:var(--dsw-alias-bg-layer-0,#111722); }.roboMarketPublisherIcon { display:grid;place-items:center;width:34px;height:34px;border-radius:10px;color:var(--dsw-alias-brand-primary,#72a2ff);background:var(--dsw-alias-interactive-bg-hover); }.roboMarketPublisherCopy { min-width:0;display:grid;gap:2px; }.roboMarketPublisherLabel { color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary));font-size:11px; }.roboMarketPublisherCopy strong { overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:14px; }.roboMarketPublisherMeta { display:flex;align-items:center;gap:6px;flex-wrap:wrap;color:var(--dsw-alias-label-secondary);font-size:12px; }.roboMarketPublisherMeta span + span::before { content:'·';margin-right:6px;color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary)); }
.roboMarketDetailGrid { display:grid;grid-template-columns:minmax(0,1fr) 220px;gap:42px; }.roboMarketDetailMain section { margin-top:24px; }.roboMarketDetailMain section + section { padding-top:22px;border-top:1px solid var(--dsw-alias-border-l1); }.roboMarketDetailGrid h2 { font-size:16px;line-height:1.35;margin:0 0 9px; }.roboMarketDetailGrid p,.roboMarketDetailGrid li { color:var(--dsw-alias-label-secondary);font-size:14px;line-height:1.65;overflow-wrap:anywhere; }.roboMarketDetailGrid ul { padding-left:19px;margin:0; }.roboMarketDetailGrid li { padding:2px 0; }.roboMarketDetailAside { align-self:start;margin-top:24px;padding-left:22px;border-left:1px solid var(--dsw-alias-border-l1); }.roboMarketDetailAside section { margin:0 0 24px; }.roboMarketDetailAside section + section { padding-top:20px;border-top:1px solid var(--dsw-alias-border-l1); }.roboMarketDetailAside h2 { color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary));font-size:12px;font-weight:650;letter-spacing:.04em; }.roboMarketDetailAside dl { margin:0;font-size:13px; }.roboMarketDetailAside dl div { display:flex;align-items:baseline;justify-content:space-between;gap:16px; }.roboMarketDetailAside dt { color:var(--dsw-alias-label-secondary); }.roboMarketDetailAside dd { margin:0;color:var(--dsw-alias-label-primary); }
.roboMarketModalFooter { flex:0 0 auto;display:flex;align-items:center;justify-content:flex-end;gap:16px;margin:0 -30px;padding:16px 30px 18px;border-top:1px solid var(--dsw-alias-border-l1);background:var(--dsw-alias-bg-layer-1,#151a24); }

.roboDevices .roboMarketHeading { align-items:center;padding-bottom:8px; }.roboDevices .roboMarketHeading h1 { margin:0; }
.roboDevices .roboMarketToolbar { margin:18px 0; }.roboDevices .roboSkillSearch { width:min(520px,100%); }
.roboDeviceCards { grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px; }
.roboDeviceCard { position:relative;display:grid;grid-template-columns:104px minmax(0,1fr);align-items:stretch;min-height:136px;padding:0;border:1px solid var(--dsw-alias-border-l1);border-radius:14px;background:var(--dsw-alias-bg-layer-1);overflow:hidden;transition:border-color .16s ease,background .16s ease; }
.roboDeviceCard::before { content:"";position:absolute;inset:0 0 auto;height:3px;background:var(--dsw-alias-border-l1); }
.roboDeviceCard:hover { border-color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary));background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-layer-1)); }
.roboDeviceCard[data-current=true] { border-color:var(--dsw-alias-brand-primary,#3267d6); }.roboDeviceCard[data-current=true]::before { background:var(--dsw-alias-brand-primary,#3267d6); }
.roboDeviceCard__image { grid-row:1 / span 2;display:grid;place-items:center;min-height:136px;overflow:hidden;background:var(--dsw-alias-bg-layer-0,#10151f);color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary)); }.roboDeviceCard__image img { width:100%;height:100%;object-fit:cover;display:block; }
.roboDeviceCard__body { grid-column:2;display:flex;flex:1;flex-direction:column;align-items:stretch;padding:15px 16px 13px; }.roboDeviceCard__meta { display:flex;align-items:center;justify-content:space-between;gap:12px; }.roboDeviceCard .roboMarketEyebrow { min-width:0; }.roboDeviceVersion { flex:none;padding:3px 8px;border:1px solid var(--dsw-alias-border-l1);border-radius:999px;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px; }.roboDeviceCard h2 { margin:10px 0 0; }.roboDeviceCard h2 .roboMarketLink { color:var(--dsw-alias-label-primary);font-size:22px;font-weight:650;letter-spacing:-.02em; }
.roboDeviceProfileChoice { display:flex;align-items:center;gap:10px;margin:20px 0 4px;color:var(--dsw-alias-label-secondary);font-size:13px; }.roboDeviceProfileChoice select { min-width:220px;padding:8px 10px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit; }.roboDeviceProfileChoice select:focus-visible { outline:2px solid var(--dsw-alias-brand-primary,#6ea0ff);outline-offset:1px; }
.roboDeviceCard footer { display:flex;align-items:center;justify-content:flex-end;gap:12px;margin-top:auto;padding-top:14px; }
.roboDeviceDetails { margin:0;padding:26px;border:0;border-radius:18px;overflow:auto;overflow-wrap:anywhere;background:var(--dsw-alias-bg-layer-1); }
.roboDeviceDetails__grid { display:grid;grid-template-columns:220px minmax(0,1fr);gap:26px; }.roboDeviceDetails__media { display:grid;place-items:center;align-self:start;aspect-ratio:1 / 1;overflow:hidden;border-radius:14px;background:var(--dsw-alias-bg-layer-0,#10151f);color:var(--dsw-alias-label-tertiary,var(--dsw-alias-label-secondary)); }.roboDeviceDetails__media img { width:100%;height:100%;object-fit:cover;display:block; }.roboDeviceDetails__content { min-width:0; }.roboDeviceDetails> .roboDeviceDetails__grid header { display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding:0 46px 18px 0;border-bottom:1px solid var(--dsw-alias-border-l1); }.roboDeviceDetails header>div { min-width:0; }.roboDeviceDetails header .roboMarketEyebrow { margin:0 0 6px; }.roboDeviceDetails header .roboMarketNote { margin:7px 0 0; }.roboDeviceDetails header .roboMarketLink { display:inline-flex;align-items:center;justify-content:center;min-height:34px;padding:0 13px;border:1px solid transparent;border-radius:8px;background:var(--dsw-alias-button-primary-fill,#3267d6);color:var(--dsw-alias-label-primary-foreground,#fff);font-size:13px;font-weight:650;text-decoration:none;white-space:nowrap; }.roboDeviceDetails header .roboMarketLink:hover { filter:brightness(1.08); }.roboDeviceDetails h2 { margin:0;font-size:26px;line-height:1.2;letter-spacing:-.02em; }
.roboDeviceDetails__facts { display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:20px 0 0;padding:0; }.roboDeviceDetails__facts div { display:grid;gap:4px;padding:10px 12px;border-radius:10px;background:var(--dsw-alias-bg-layer-0,#10151f); }.roboDeviceDetails__facts dt { color:var(--dsw-alias-label-secondary);font-size:12px; }.roboDeviceDetails__facts dd { margin:0;color:var(--dsw-alias-label-primary);font-size:14px;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap; }
.roboDeviceDetails__description { margin-top:22px;padding-top:18px;border-top:1px solid var(--dsw-alias-border-l1); }.roboDeviceDetails__description h3 { margin:0 0 8px;font-size:15px; }.roboDeviceDetails__description p { margin:0;color:var(--dsw-alias-label-secondary);font-size:14px;line-height:1.7; }
.roboDeviceTutorialHeader { display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap; }
.roboDeviceDescription { white-space:pre-wrap;line-height:1.7; }.roboDeviceDetails pre { max-height:240px;overflow:auto;white-space:pre-wrap;font:13px/1.6 monospace; }.roboDeviceDetails iframe { width:100%;height:min(65vh,720px);min-height:300px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;background:white; }
@media(max-width:900px) { .roboMarketInner { padding:20px 24px 44px; }.roboMarketCards { grid-template-columns:repeat(3,minmax(0,1fr)); }.roboDeviceCards { grid-template-columns:repeat(2,minmax(0,1fr)); }.roboMarketTopActions { flex-wrap:wrap;justify-content:flex-end; }.roboMarketFilters { align-items:flex-start;flex-direction:column; }.roboMarketDetailGrid { grid-template-columns:minmax(0,1fr);gap:0; }.roboMarketDetailAside { margin-top:24px;padding:20px 0 0;border-left:0;border-top:1px solid var(--dsw-alias-border-l1); }.roboDeviceDetails__grid { grid-template-columns:160px minmax(0,1fr);gap:20px; } }
@media(max-width:680px) { .roboMarketTop { grid-template-columns:auto minmax(0,1fr) auto;row-gap:8px;padding-bottom:10px; }.roboMarketTop .roboSkillSearch { grid-column:2 / 4; }.roboMarketTop .roboMarketMine { grid-column:2;justify-self:end; }.roboMarketPrimaryTabs { align-self:auto; }.roboMarketTopActions { justify-content:stretch; }.roboMarket .roboSkillSearch { min-width:0;flex:1 1 100%; }.roboMarketMine,.roboMarketCreate { flex:1;justify-content:center; }.roboMarketCategories { width:100%; }.roboMarketCards,.roboDeviceCards { grid-template-columns:repeat(2,minmax(0,1fr)); }.roboMarket h1 { font-size:26px; }.roboMarketRobot { width:100%; }.roboMarketRobot select { max-width:none;flex:1; }.roboMarketModal { padding:24px 20px 24px; }.roboMarketModalFooter { margin:0 -20px;padding:14px 20px 16px; }.roboMarketDetailHeading { align-items:flex-start; }.roboMarketIcon { width:40px;height:40px; }.roboDeviceDetails { padding:20px; }.roboDeviceDetails__grid { grid-template-columns:minmax(0,1fr); }.roboDeviceDetails__media { width:min(220px,100%); }.roboDeviceDetails> .roboDeviceDetails__grid header { padding-right:40px;flex-direction:column; }.roboDeviceDetails header .roboMarketLink { width:100%; }.roboDeviceDetails__facts { grid-template-columns:repeat(3,minmax(0,1fr)); }.roboDeviceProfileChoice { align-items:flex-start;flex-direction:column; }.roboDeviceProfileChoice select { min-width:0;width:100%; } }
@media(max-width:520px) { .roboMarketCards,.roboDeviceCards { grid-template-columns:minmax(0,1fr); } }
@media(prefers-reduced-motion:reduce) { .roboDeviceHeader { display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;border-bottom:1px solid var(--dsw-alias-border-l1);margin-bottom:20px; }
.roboDeviceTabs { display:flex;align-items:center;gap:24px;height:48px; }
.roboDeviceTabs button { position:relative;display:inline-flex;align-items:center;height:48px;border:0;background:transparent;color:var(--dsw-alias-label-secondary);padding:0;font-size:14px;line-height:20px; }
.roboDeviceTabs button[aria-selected=true] { color:var(--dsw-alias-label-primary);border-bottom-color:currentColor;font-weight:600; }
.roboDeviceHeader .roboDeviceHeadingActions { font-size:13px; }
.roboMarket * { scroll-behavior:auto!important;transition:none!important; } }

.roboLocalSkills { margin:20px 0;padding-bottom:16px;border-bottom:1px solid var(--dsw-alias-border-l1); }
.roboLocalSkills h2 { font-size:16px; }.roboLocalSkills h2 span,.roboLocalSkills small,.roboLocalSkills p { color:var(--dsw-alias-label-secondary); }
.roboLocalSkillRow { display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 0;overflow-wrap:anywhere; }.roboLocalSkillRow>div { min-width:0; }.roboLocalSkillRow h3 { margin:0;font-size:14px; }.roboLocalSkillRow p { margin:4px 0;font-size:13px; }.roboLocalSkillRemove { display:flex;flex-wrap:wrap;gap:8px;align-items:center;font-size:13px; }
.roboLocalSkillDialog { box-sizing:border-box;width:min(520px,calc(100vw - 32px));max-height:calc(100vh - 32px);overflow:auto;padding:28px;border:1px solid var(--dsw-alias-border-l1);border-radius:16px;background:var(--dsw-alias-bg-layer-0);color:var(--dsw-alias-label-primary);box-shadow:0 24px 70px #0004; }
.roboLocalSkillDialog::backdrop { background:rgba(8,15,28,.46);backdrop-filter:blur(4px); }.roboLocalSkillDialog h2 { margin:0 32px 12px 0;font-size:20px; }.roboLocalSkillDialog p { font-size:14px;line-height:1.6;color:var(--dsw-alias-label-secondary); }.roboLocalSkillDialog form { margin-top:20px; }.roboLocalSkillDialog label { display:flex;flex-direction:column;gap:8px;margin:16px 0;font-size:13px; }
.roboLocalSkillDialog input { width:100%;box-sizing:border-box;padding:10px 12px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;color:inherit;background:var(--dsw-alias-bg-layer-1);font:inherit; }.roboLocalSkillDialog footer { display:flex;justify-content:flex-end;gap:8px;margin-top:20px; }.roboLocalSkillDialog .roboLocalSkillPublish { margin:22px 0 0;padding-top:16px;border-top:1px solid var(--dsw-alias-border-l1);font-size:13px; }.roboLocalSkillPublish a { color:inherit;text-decoration:underline;text-underline-offset:3px; }.roboLocalSkillDialog [role=alert] { color:var(--dsw-alias-state-warning-primary,#a34d14); }
`
