export function installRoboCodingAccountStyles(): () => void {
  const style = document.createElement('style')
  style.dataset.robocodingAccount = 'true'
  style.textContent = `
.roboAccount{--account-border:var(--dsw-alias-border-l1);--account-surface:var(--dsw-alias-bg-layer-1);--account-soft:var(--dsw-alias-interactive-bg-hover);--account-muted:var(--dsw-alias-label-secondary);--account-primary:var(--dsw-alias-button-primary-fill);display:grid;gap:20px;max-width:760px;min-width:0;container-type:inline-size}
.roboAccount *{box-sizing:border-box}.roboAccountPageHeader{display:flex;align-items:center;min-height:32px;padding:0}.roboAccount h2,.roboAccount h3,.roboAccount p{margin:0}.roboAccount h2{font-size:22px;line-height:32px;letter-spacing:-.02em}.roboAccount h3{font-size:16px;line-height:24px}
.roboAccount button,.roboAccount a{align-items:center;background:var(--account-surface);border:1px solid var(--account-border);border-radius:12px;color:inherit;display:inline-flex;font:inherit;gap:6px;justify-content:center;padding:8px 12px;min-height:44px;line-height:24px;text-decoration:none}.roboAccount button{cursor:pointer}.roboAccount button:hover:not(:disabled),.roboAccount a:hover{background:var(--account-soft)}.roboAccount button:focus-visible,.roboAccount a:focus-visible,.roboAccount summary:focus-visible,.roboAccount input:focus-visible{outline:2px solid var(--account-primary);outline-offset:2px}.roboAccount button:disabled{cursor:not-allowed;opacity:.5}.roboAccount .roboAccountPrimary{background:var(--account-primary);color:var(--dsw-alias-label-primary-foreground)}
.roboAccountNotice{background:var(--account-soft);border:1px solid var(--account-border);border-radius:12px;color:var(--account-muted);padding:10px 12px}.roboAccountNoticeError{color:var(--dsw-alias-state-error-primary)}.roboAccountLoading,.roboAccountEmpty{color:var(--account-muted)}
.roboAccountSignIn,.roboAccountAuthorization,.roboAccountPanel{background:var(--account-surface);border:1px solid var(--account-border);border-radius:20px;padding:20px}.roboAccountSignIn{align-items:center;display:grid;gap:16px;grid-template-columns:44px minmax(0,1fr) auto}.roboAccountSignInMark{align-items:center;background:var(--account-primary);border-radius:50%;corner-shape:round;color:var(--dsw-alias-label-primary-foreground);display:flex;height:44px;justify-content:center;width:44px}.roboAccountSignInCopy{display:grid;gap:0;min-width:0}.roboAccountSignInCopy h3{line-height:24px}.roboAccountServiceStatus{font-size:13px;line-height:20px;color:var(--account-muted)}.roboAccountSignIn>.roboAccountPrimary{min-height:44px;white-space:nowrap}.roboAccountSignInCopy p,.roboAccountAuthorization p{color:var(--account-muted)}
.roboAccountAuthorization{align-items:center;display:grid;gap:12px;grid-template-columns:minmax(0,1fr) auto}.roboAccountAuthorization>div{display:grid;gap:3px}.roboAccountAuthorization>div span{color:var(--account-muted);font-size:13px}.roboAccountAuthorization>div strong{font-size:24px;letter-spacing:.12em}.roboAccountAuthorization p{grid-column:1}.roboAccountAuthorization button{grid-column:2;grid-row:1/3}
.roboAccountProfile{align-items:center;background:var(--account-surface);border:1px solid var(--account-border);border-radius:20px;box-shadow:0 8px 24px rgb(0 0 0/.04);display:grid;gap:16px;grid-template-columns:48px minmax(0,1fr) auto auto;padding:20px}.roboAccountAvatar{align-items:center;background:var(--account-primary);border-radius:50%;corner-shape:round;color:var(--dsw-alias-label-primary-foreground);display:flex;font-size:18px;font-weight:700;height:48px;justify-content:center;position:relative;width:48px}.roboAccountAvatar span{background:var(--dsw-alias-state-success-primary);border:2px solid var(--account-surface);border-radius:50%;corner-shape:round;bottom:-1px;height:11px;position:absolute;right:-1px;width:11px}.roboAccountIdentity,.roboAccountBalance{display:grid;gap:3px}.roboAccountIdentity{min-width:0}.roboAccountIdentity>strong,.roboAccountIdentity>span{display:block;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.roboAccountIdentity>strong{font-size:16px;line-height:24px}.roboAccountIdentity>span,.roboAccountBalance>span{color:var(--account-muted);font-size:13px}.roboAccountBalance{min-width:116px;padding-left:18px;position:relative}.roboAccountBalance:before{background:var(--account-border);content:'';height:40px;left:0;position:absolute;top:50%;transform:translateY(-50%);width:1px}.roboAccountBalance>strong{font-size:21px;font-variant-numeric:tabular-nums;letter-spacing:-.02em}.roboAccountBalance small{color:var(--account-muted);font-size:12px;font-weight:500}.roboAccountActions{display:flex;align-items:center;gap:8px}.roboAccountActions button:first-child{width:44px;padding-inline:0}
.roboAccountPanel{display:grid;gap:16px}.roboAccountHeading,.roboAccountSectionTitle,.roboAccountTeam,.roboAccountConsent{align-items:center;display:flex}.roboAccountHeading,.roboAccountTeam,.roboAccountConsent{justify-content:space-between}.roboAccountSectionTitle{gap:8px}.roboAccountSectionTitle svg{color:var(--account-muted)}.roboAccountChoices,.roboAccountTeamList{display:grid;gap:8px}.roboAccountChoice{align-items:center;border:1px solid var(--account-border);border-radius:11px;cursor:pointer;display:flex;gap:12px;padding:12px 16px}.roboAccountChoice:has(input:checked){border-color:var(--account-primary);box-shadow:inset 0 0 0 1px var(--account-primary)}.roboAccountChoice input{accent-color:var(--account-primary);margin:0}.roboAccountChoice span,.roboAccountTeam>div{display:grid;gap:2px}.roboAccountChoice small,.roboAccountTeam small{color:var(--account-muted)}
.roboAccountConsent{background:var(--account-soft);border-radius:11px;gap:16px;padding:12px}.roboAccountConsent>div{display:flex;gap:7px}.roboAccountConsent>div:first-child{align-items:flex-start;display:grid;gap:3px}.roboAccountConsent span{color:var(--account-muted);font-size:13px}.roboAccountTeam{border-top:1px solid var(--account-border);padding-top:11px}.roboAccountTeam:first-child{border-top:0;padding-top:0}.roboAccountTeam>span{font-variant-numeric:tabular-nums}
@container(max-width:520px){.roboAccountSignIn{grid-template-columns:44px minmax(0,1fr)}.roboAccountSignIn>.roboAccountPrimary{grid-column:1/-1}.roboAccountSignIn>.roboAccountPrimary{width:100%}.roboAccountProfile{grid-template-columns:auto minmax(0,1fr)}.roboAccountBalance{grid-column:1/-1;padding-left:0}.roboAccountBalance:before{display:none}.roboAccountActions{grid-column:1/-1}.roboAccountConsent{align-items:stretch;flex-direction:column}.roboAccountConsent>div:last-child{justify-content:flex-end}}
`
  document.head.append(style)
  return () => style.remove()
}
